//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kask.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class AESDatabaseEntities : DbContext
    {
        public AESDatabaseEntities()
            : base("name=AESDatabaseEntities")
        {
        }

        static AESDatabaseEntities ()
        {
            var _ = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
            var __ = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Applied> Applieds { get; set; }
        public virtual DbSet<Job_Requirements> Job_Requirements { get; set; }
    }
}
