<?xml version="1.0" encoding="utf-8"?><Database Name="AESDatabase" Class="AESDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=AESDatabase;Integrated Security=True;Persist Security Info=True" SettingsObjectName="Kask.DAL.Properties.Settings" SettingsPropertyName="AESDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Applicant" Member="Applicants">
    <Type Name="Applicant">
      <Column Name="Applicant_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SSN" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ApplicantAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameAlias" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Applicant_Applied" Member="Applieds" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Applied" />
      <Association Name="Applicant_Associate" Member="Associates" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Associate" />
      <Association Name="Applicant_Education" Member="Educations" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Education" />
      <Association Name="Applicant_Employment" Member="Employments" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Employment" />
      <Association Name="Applicant_Expertise" Member="Expertises" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Expertise" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_UsersInRoles" Member="webpages_UsersInRoles">
    <Type Name="webpages_UsersInRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserProfile_webpages_UsersInRole" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_Role" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Applications">
    <Type Name="Application">
      <Column Name="Application_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SalaryExpectation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FullTime" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AvailableForDays" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AvailableForEvenings" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AvailableForWeekends" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MondayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="TuesdayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="WednesdayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ThursdayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="FridayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="SaturdayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="SundayFrom" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="MondayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="TuesdayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="WednesdayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ThursdayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="FridayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="SaturdayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="SundayTo" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Application_Applied" Member="Applieds" ThisKey="Application_ID" OtherKey="Application_ID" Type="Applied" />
    </Type>
  </Table>
  <Table Name="dbo.Applied" Member="Applieds">
    <Type Name="Applied">
      <Column Name="Applied_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Applicant_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Application_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Job_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateApplied" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Applicant_Applied" Member="Applicant" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Applicant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Application_Applied" Member="Application" ThisKey="Application_ID" OtherKey="Application_ID" Type="Application" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Job_Applied" Member="Job" ThisKey="Job_ID" OtherKey="Job_ID" Type="Job" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Associate" Member="Associates">
    <Type Name="Associate">
      <Column Name="Associate_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Applicant_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reference_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Applicant_Associate" Member="Applicant" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Applicant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Reference_Associate" Member="Reference" ThisKey="Reference_ID" OtherKey="Reference_ID" Type="Reference" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Education" Member="Educations">
    <Type Name="Education">
      <Column Name="Education_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Applicant_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="School_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YearsAttendedFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="YearsAttendedTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Graduated" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DegreeAndMajor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Applicant_Education" Member="Applicant" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Applicant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="School_Education" Member="School" ThisKey="School_ID" OtherKey="School_ID" Type="School" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employer" Member="Employers">
    <Type Name="Employer">
      <Column Name="Employer_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EmployerAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employer_Employment" Member="Employments" ThisKey="Employer_ID" OtherKey="Employer_ID" Type="Employment" />
    </Type>
  </Table>
  <Table Name="dbo.Employment" Member="Employments">
    <Type Name="Employment">
      <Column Name="Employment_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Applicant_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Employer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MayWeContactCurrentEmployer" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="EmployedFrom" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EmployedTo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StartingSalary" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EndingSalary" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ReasonForLeaving" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Responsibilities" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Applicant_Employment" Member="Applicant" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Applicant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Employer_Employment" Member="Employer" ThisKey="Employer_ID" OtherKey="Employer_ID" Type="Employer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Expertise" Member="Expertises">
    <Type Name="Expertise">
      <Column Name="Expertise_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Applicant_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Skill_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Applicant_Expertise" Member="Applicant" ThisKey="Applicant_ID" OtherKey="Applicant_ID" Type="Applicant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Skill_Expertise" Member="Skill" ThisKey="Skill_ID" OtherKey="Skill_ID" Type="Skill" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reference" Member="References">
    <Type Name="Reference">
      <Column Name="Reference_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="YearsKnown" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Reference_Associate" Member="Associates" ThisKey="Reference_ID" OtherKey="Reference_ID" Type="Associate" />
    </Type>
  </Table>
  <Table Name="dbo.School" Member="Schools">
    <Type Name="School">
      <Column Name="School_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="School_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="School_Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="School_Education" Member="Educations" ThisKey="School_ID" OtherKey="School_ID" Type="Education" />
    </Type>
  </Table>
  <Table Name="dbo.Skill" Member="Skills">
    <Type Name="Skill">
      <Column Name="Skill_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SkillName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Skill_Expertise" Member="Expertises" ThisKey="Skill_ID" OtherKey="Skill_ID" Type="Expertise" />
      <Association Name="Skill_JobRequirement" Member="JobRequirements" ThisKey="Skill_ID" OtherKey="Skill_ID" Type="JobRequirement" />
    </Type>
  </Table>
  <Table Name="dbo.StoreManager" Member="StoreManagers">
    <Type Name="StoreManager">
      <Column Name="StoreManager_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StoreManager_Store" Member="Stores" ThisKey="StoreManager_ID" OtherKey="Manager_ID" Type="Store" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="UserProfile_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Membership" Member="webpages_Memberships">
    <Type Name="webpages_Membership">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_OAuthMembership" Member="webpages_OAuthMemberships">
    <Type Name="webpages_OAuthMembership">
      <Column Name="Provider" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderUserId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Roles" Member="webpages_Roles">
    <Type Name="webpages_Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.Job" Member="Jobs">
    <Type Name="Job">
      <Column Name="Job_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Job_Applied" Member="Applieds" ThisKey="Job_ID" OtherKey="Job_ID" Type="Applied" />
      <Association Name="Job_JobOpening" Member="JobOpenings" ThisKey="Job_ID" OtherKey="Job_ID" Type="JobOpening" />
    </Type>
  </Table>
  <Table Name="dbo.JobRequirement" Member="JobRequirements">
    <Type Name="JobRequirement">
      <Column Name="JobRequirement_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JobOpening_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Skill_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Skill_JobRequirement" Member="Skill" ThisKey="Skill_ID" OtherKey="Skill_ID" Type="Skill" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="JobOpening_JobRequirement" Member="JobOpening" ThisKey="JobOpening_ID" OtherKey="JobOpening_ID" Type="JobOpening" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobOpening" Member="JobOpenings">
    <Type Name="JobOpening">
      <Column Name="JobOpening_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OpenDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Job_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Approved" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Store_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="JobOpening_JobRequirement" Member="JobRequirements" ThisKey="JobOpening_ID" OtherKey="JobOpening_ID" Type="JobRequirement" />
      <Association Name="Job_JobOpening" Member="Job" ThisKey="Job_ID" OtherKey="Job_ID" Type="Job" IsForeignKey="true" />
      <Association Name="Store_JobOpening" Member="Store" ThisKey="Store_ID" OtherKey="Store_ID" Type="Store" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Store" Member="Stores">
    <Type Name="Store">
      <Column Name="Store_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Manager_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Store_JobOpening" Member="JobOpenings" ThisKey="Store_ID" OtherKey="Store_ID" Type="JobOpening" />
      <Association Name="StoreManager_Store" Member="StoreManager" ThisKey="Manager_ID" OtherKey="StoreManager_ID" Type="StoreManager" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>