//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kask.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public Employer()
        {
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int Employer_ID { get; set; }
        public string Employer_Name { get; set; }
    
        public virtual ICollection<Applicant> Applicants { get; set; }
    }
}
