//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kask.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Applieds = new HashSet<Applied>();
            this.Job_Requirements = new HashSet<Job_Requirements>();
        }
    
        public int Job_ID { get; set; }
        public string Job_Title { get; set; }
    
        public virtual ICollection<Applied> Applieds { get; set; }
        public virtual ICollection<Job_Requirements> Job_Requirements { get; set; }
    }
}
