//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kask.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Requirements
    {
        public int Job_ID { get; set; }
        public int Skill_ID { get; set; }
        public string Notes { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
