//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kask.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.Job_Requirements = new HashSet<Job_Requirements>();
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int Skill_ID { get; set; }
        public string SkillName { get; set; }
    
        public virtual ICollection<Job_Requirements> Job_Requirements { get; set; }
        public virtual ICollection<Applicant> Applicants { get; set; }
    }
}
