#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kask.DAL2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AESDatabase")]
	public partial class AESDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertApplicant(Applicant instance);
    partial void UpdateApplicant(Applicant instance);
    partial void DeleteApplicant(Applicant instance);
    partial void InsertApplication(Application instance);
    partial void UpdateApplication(Application instance);
    partial void DeleteApplication(Application instance);
    partial void InsertEmployer(Employer instance);
    partial void UpdateEmployer(Employer instance);
    partial void DeleteEmployer(Employer instance);
    partial void InsertJob(Job instance);
    partial void UpdateJob(Job instance);
    partial void DeleteJob(Job instance);
    partial void InsertReference(Reference instance);
    partial void UpdateReference(Reference instance);
    partial void DeleteReference(Reference instance);
    partial void InsertSchool(School instance);
    partial void UpdateSchool(School instance);
    partial void DeleteSchool(School instance);
    partial void InsertSkill(Skill instance);
    partial void UpdateSkill(Skill instance);
    partial void DeleteSkill(Skill instance);
    #endregion
		
		public AESDatabaseDataContext() : 
				base(global::Kask.DAL2.Properties.Settings.Default.AESDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AESDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AESDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AESDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AESDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Applicant> Applicants
		{
			get
			{
				return this.GetTable<Applicant>();
			}
		}
		
		public System.Data.Linq.Table<Application> Applications
		{
			get
			{
				return this.GetTable<Application>();
			}
		}
		
		public System.Data.Linq.Table<Applied> Applieds
		{
			get
			{
				return this.GetTable<Applied>();
			}
		}
		
		public System.Data.Linq.Table<Associate> Associates
		{
			get
			{
				return this.GetTable<Associate>();
			}
		}
		
		public System.Data.Linq.Table<Education> Educations
		{
			get
			{
				return this.GetTable<Education>();
			}
		}
		
		public System.Data.Linq.Table<Employer> Employers
		{
			get
			{
				return this.GetTable<Employer>();
			}
		}
		
		public System.Data.Linq.Table<Employment> Employments
		{
			get
			{
				return this.GetTable<Employment>();
			}
		}
		
		public System.Data.Linq.Table<Expertise> Expertises
		{
			get
			{
				return this.GetTable<Expertise>();
			}
		}
		
		public System.Data.Linq.Table<Job> Jobs
		{
			get
			{
				return this.GetTable<Job>();
			}
		}
		
		public System.Data.Linq.Table<JobRequirement> JobRequirements
		{
			get
			{
				return this.GetTable<JobRequirement>();
			}
		}
		
		public System.Data.Linq.Table<Reference> References
		{
			get
			{
				return this.GetTable<Reference>();
			}
		}
		
		public System.Data.Linq.Table<School> Schools
		{
			get
			{
				return this.GetTable<School>();
			}
		}
		
		public System.Data.Linq.Table<Skill> Skills
		{
			get
			{
				return this.GetTable<Skill>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Applicant")]
	public partial class Applicant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Applicant_ID;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _SSN;
		
		private string _Gender;
		
		private string _ApplicantAddress;
		
		private string _Phone;
		
		private string _NameAlias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicant_IDChanging(int value);
    partial void OnApplicant_IDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnApplicantAddressChanging(string value);
    partial void OnApplicantAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnNameAliasChanging(string value);
    partial void OnNameAliasChanged();
    #endregion
		
		public Applicant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Applicant_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Applicant_ID
		{
			get
			{
				return this._Applicant_ID;
			}
			set
			{
				if ((this._Applicant_ID != value))
				{
					this.OnApplicant_IDChanging(value);
					this.SendPropertyChanging();
					this._Applicant_ID = value;
					this.SendPropertyChanged("Applicant_ID");
					this.OnApplicant_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicantAddress", DbType="VarChar(255)")]
		public string ApplicantAddress
		{
			get
			{
				return this._ApplicantAddress;
			}
			set
			{
				if ((this._ApplicantAddress != value))
				{
					this.OnApplicantAddressChanging(value);
					this.SendPropertyChanging();
					this._ApplicantAddress = value;
					this.SendPropertyChanged("ApplicantAddress");
					this.OnApplicantAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameAlias", DbType="VarChar(255)")]
		public string NameAlias
		{
			get
			{
				return this._NameAlias;
			}
			set
			{
				if ((this._NameAlias != value))
				{
					this.OnNameAliasChanging(value);
					this.SendPropertyChanging();
					this._NameAlias = value;
					this.SendPropertyChanged("NameAlias");
					this.OnNameAliasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Application")]
	public partial class Application : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Application_ID;
		
		private string _ApplicationStatus;
		
		private string _SalaryExpectation;
		
		private System.Nullable<byte> _FullTime;
		
		private System.Nullable<byte> _AvailableForDays;
		
		private System.Nullable<byte> _AvailableForEvenings;
		
		private System.Nullable<byte> _AvailableForWeekends;
		
		private System.Nullable<System.TimeSpan> _MondayFrom;
		
		private System.Nullable<System.TimeSpan> _TuesdayFrom;
		
		private System.Nullable<System.TimeSpan> _WednesdayFrom;
		
		private System.Nullable<System.TimeSpan> _ThursdayFrom;
		
		private System.Nullable<System.TimeSpan> _FridayFrom;
		
		private System.Nullable<System.TimeSpan> _SaturdayFrom;
		
		private System.Nullable<System.TimeSpan> _SundayFrom;
		
		private System.Nullable<System.TimeSpan> _MondayTo;
		
		private System.Nullable<System.TimeSpan> _TuesdayTo;
		
		private System.Nullable<System.TimeSpan> _WednesdayTo;
		
		private System.Nullable<System.TimeSpan> _ThursdayTo;
		
		private System.Nullable<System.TimeSpan> _FridayTo;
		
		private System.Nullable<System.TimeSpan> _SaturdayTo;
		
		private System.Nullable<System.TimeSpan> _SundayTo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplication_IDChanging(int value);
    partial void OnApplication_IDChanged();
    partial void OnApplicationStatusChanging(string value);
    partial void OnApplicationStatusChanged();
    partial void OnSalaryExpectationChanging(string value);
    partial void OnSalaryExpectationChanged();
    partial void OnFullTimeChanging(System.Nullable<byte> value);
    partial void OnFullTimeChanged();
    partial void OnAvailableForDaysChanging(System.Nullable<byte> value);
    partial void OnAvailableForDaysChanged();
    partial void OnAvailableForEveningsChanging(System.Nullable<byte> value);
    partial void OnAvailableForEveningsChanged();
    partial void OnAvailableForWeekendsChanging(System.Nullable<byte> value);
    partial void OnAvailableForWeekendsChanged();
    partial void OnMondayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnMondayFromChanged();
    partial void OnTuesdayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTuesdayFromChanged();
    partial void OnWednesdayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnWednesdayFromChanged();
    partial void OnThursdayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThursdayFromChanged();
    partial void OnFridayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnFridayFromChanged();
    partial void OnSaturdayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSaturdayFromChanged();
    partial void OnSundayFromChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSundayFromChanged();
    partial void OnMondayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnMondayToChanged();
    partial void OnTuesdayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTuesdayToChanged();
    partial void OnWednesdayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnWednesdayToChanged();
    partial void OnThursdayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThursdayToChanged();
    partial void OnFridayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnFridayToChanged();
    partial void OnSaturdayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSaturdayToChanged();
    partial void OnSundayToChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSundayToChanged();
    #endregion
		
		public Application()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Application_ID
		{
			get
			{
				return this._Application_ID;
			}
			set
			{
				if ((this._Application_ID != value))
				{
					this.OnApplication_IDChanging(value);
					this.SendPropertyChanging();
					this._Application_ID = value;
					this.SendPropertyChanged("Application_ID");
					this.OnApplication_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationStatus", DbType="VarChar(10)")]
		public string ApplicationStatus
		{
			get
			{
				return this._ApplicationStatus;
			}
			set
			{
				if ((this._ApplicationStatus != value))
				{
					this.OnApplicationStatusChanging(value);
					this.SendPropertyChanging();
					this._ApplicationStatus = value;
					this.SendPropertyChanged("ApplicationStatus");
					this.OnApplicationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryExpectation", DbType="VarChar(50)")]
		public string SalaryExpectation
		{
			get
			{
				return this._SalaryExpectation;
			}
			set
			{
				if ((this._SalaryExpectation != value))
				{
					this.OnSalaryExpectationChanging(value);
					this.SendPropertyChanging();
					this._SalaryExpectation = value;
					this.SendPropertyChanged("SalaryExpectation");
					this.OnSalaryExpectationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullTime", DbType="TinyInt")]
		public System.Nullable<byte> FullTime
		{
			get
			{
				return this._FullTime;
			}
			set
			{
				if ((this._FullTime != value))
				{
					this.OnFullTimeChanging(value);
					this.SendPropertyChanging();
					this._FullTime = value;
					this.SendPropertyChanged("FullTime");
					this.OnFullTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableForDays", DbType="TinyInt")]
		public System.Nullable<byte> AvailableForDays
		{
			get
			{
				return this._AvailableForDays;
			}
			set
			{
				if ((this._AvailableForDays != value))
				{
					this.OnAvailableForDaysChanging(value);
					this.SendPropertyChanging();
					this._AvailableForDays = value;
					this.SendPropertyChanged("AvailableForDays");
					this.OnAvailableForDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableForEvenings", DbType="TinyInt")]
		public System.Nullable<byte> AvailableForEvenings
		{
			get
			{
				return this._AvailableForEvenings;
			}
			set
			{
				if ((this._AvailableForEvenings != value))
				{
					this.OnAvailableForEveningsChanging(value);
					this.SendPropertyChanging();
					this._AvailableForEvenings = value;
					this.SendPropertyChanged("AvailableForEvenings");
					this.OnAvailableForEveningsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableForWeekends", DbType="TinyInt")]
		public System.Nullable<byte> AvailableForWeekends
		{
			get
			{
				return this._AvailableForWeekends;
			}
			set
			{
				if ((this._AvailableForWeekends != value))
				{
					this.OnAvailableForWeekendsChanging(value);
					this.SendPropertyChanging();
					this._AvailableForWeekends = value;
					this.SendPropertyChanged("AvailableForWeekends");
					this.OnAvailableForWeekendsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> MondayFrom
		{
			get
			{
				return this._MondayFrom;
			}
			set
			{
				if ((this._MondayFrom != value))
				{
					this.OnMondayFromChanging(value);
					this.SendPropertyChanging();
					this._MondayFrom = value;
					this.SendPropertyChanged("MondayFrom");
					this.OnMondayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> TuesdayFrom
		{
			get
			{
				return this._TuesdayFrom;
			}
			set
			{
				if ((this._TuesdayFrom != value))
				{
					this.OnTuesdayFromChanging(value);
					this.SendPropertyChanging();
					this._TuesdayFrom = value;
					this.SendPropertyChanged("TuesdayFrom");
					this.OnTuesdayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> WednesdayFrom
		{
			get
			{
				return this._WednesdayFrom;
			}
			set
			{
				if ((this._WednesdayFrom != value))
				{
					this.OnWednesdayFromChanging(value);
					this.SendPropertyChanging();
					this._WednesdayFrom = value;
					this.SendPropertyChanged("WednesdayFrom");
					this.OnWednesdayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThursdayFrom
		{
			get
			{
				return this._ThursdayFrom;
			}
			set
			{
				if ((this._ThursdayFrom != value))
				{
					this.OnThursdayFromChanging(value);
					this.SendPropertyChanging();
					this._ThursdayFrom = value;
					this.SendPropertyChanged("ThursdayFrom");
					this.OnThursdayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> FridayFrom
		{
			get
			{
				return this._FridayFrom;
			}
			set
			{
				if ((this._FridayFrom != value))
				{
					this.OnFridayFromChanging(value);
					this.SendPropertyChanging();
					this._FridayFrom = value;
					this.SendPropertyChanged("FridayFrom");
					this.OnFridayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaturdayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> SaturdayFrom
		{
			get
			{
				return this._SaturdayFrom;
			}
			set
			{
				if ((this._SaturdayFrom != value))
				{
					this.OnSaturdayFromChanging(value);
					this.SendPropertyChanging();
					this._SaturdayFrom = value;
					this.SendPropertyChanged("SaturdayFrom");
					this.OnSaturdayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SundayFrom", DbType="Time")]
		public System.Nullable<System.TimeSpan> SundayFrom
		{
			get
			{
				return this._SundayFrom;
			}
			set
			{
				if ((this._SundayFrom != value))
				{
					this.OnSundayFromChanging(value);
					this.SendPropertyChanging();
					this._SundayFrom = value;
					this.SendPropertyChanged("SundayFrom");
					this.OnSundayFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> MondayTo
		{
			get
			{
				return this._MondayTo;
			}
			set
			{
				if ((this._MondayTo != value))
				{
					this.OnMondayToChanging(value);
					this.SendPropertyChanging();
					this._MondayTo = value;
					this.SendPropertyChanged("MondayTo");
					this.OnMondayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> TuesdayTo
		{
			get
			{
				return this._TuesdayTo;
			}
			set
			{
				if ((this._TuesdayTo != value))
				{
					this.OnTuesdayToChanging(value);
					this.SendPropertyChanging();
					this._TuesdayTo = value;
					this.SendPropertyChanged("TuesdayTo");
					this.OnTuesdayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> WednesdayTo
		{
			get
			{
				return this._WednesdayTo;
			}
			set
			{
				if ((this._WednesdayTo != value))
				{
					this.OnWednesdayToChanging(value);
					this.SendPropertyChanging();
					this._WednesdayTo = value;
					this.SendPropertyChanged("WednesdayTo");
					this.OnWednesdayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThursdayTo
		{
			get
			{
				return this._ThursdayTo;
			}
			set
			{
				if ((this._ThursdayTo != value))
				{
					this.OnThursdayToChanging(value);
					this.SendPropertyChanging();
					this._ThursdayTo = value;
					this.SendPropertyChanged("ThursdayTo");
					this.OnThursdayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> FridayTo
		{
			get
			{
				return this._FridayTo;
			}
			set
			{
				if ((this._FridayTo != value))
				{
					this.OnFridayToChanging(value);
					this.SendPropertyChanging();
					this._FridayTo = value;
					this.SendPropertyChanged("FridayTo");
					this.OnFridayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaturdayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> SaturdayTo
		{
			get
			{
				return this._SaturdayTo;
			}
			set
			{
				if ((this._SaturdayTo != value))
				{
					this.OnSaturdayToChanging(value);
					this.SendPropertyChanging();
					this._SaturdayTo = value;
					this.SendPropertyChanged("SaturdayTo");
					this.OnSaturdayToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SundayTo", DbType="Time")]
		public System.Nullable<System.TimeSpan> SundayTo
		{
			get
			{
				return this._SundayTo;
			}
			set
			{
				if ((this._SundayTo != value))
				{
					this.OnSundayToChanging(value);
					this.SendPropertyChanging();
					this._SundayTo = value;
					this.SendPropertyChanged("SundayTo");
					this.OnSundayToChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Applied")]
	public partial class Applied
	{
		
		private int _Applicant_ID;
		
		private int _Application_ID;
		
		private int _Job_ID;
		
		private System.DateTime _DateApplied;
		
		public Applied()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Applicant_ID", DbType="Int NOT NULL")]
		public int Applicant_ID
		{
			get
			{
				return this._Applicant_ID;
			}
			set
			{
				if ((this._Applicant_ID != value))
				{
					this._Applicant_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_ID", DbType="Int NOT NULL")]
		public int Application_ID
		{
			get
			{
				return this._Application_ID;
			}
			set
			{
				if ((this._Application_ID != value))
				{
					this._Application_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_ID", DbType="Int NOT NULL")]
		public int Job_ID
		{
			get
			{
				return this._Job_ID;
			}
			set
			{
				if ((this._Job_ID != value))
				{
					this._Job_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateApplied", DbType="Date NOT NULL")]
		public System.DateTime DateApplied
		{
			get
			{
				return this._DateApplied;
			}
			set
			{
				if ((this._DateApplied != value))
				{
					this._DateApplied = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Associate")]
	public partial class Associate
	{
		
		private int _Applicant_ID;
		
		private int _Reference_ID;
		
		private string _Name;
		
		private string _Phone;
		
		private string _Title;
		
		public Associate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Applicant_ID", DbType="Int NOT NULL")]
		public int Applicant_ID
		{
			get
			{
				return this._Applicant_ID;
			}
			set
			{
				if ((this._Applicant_ID != value))
				{
					this._Applicant_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference_ID", DbType="Int NOT NULL")]
		public int Reference_ID
		{
			get
			{
				return this._Reference_ID;
			}
			set
			{
				if ((this._Reference_ID != value))
				{
					this._Reference_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Education")]
	public partial class Education
	{
		
		private int _Applicant_ID;
		
		private int _School_ID;
		
		private System.Nullable<System.DateTime> _YearsAttendedFrom;
		
		private System.Nullable<System.DateTime> _YearsAttendedTo;
		
		private System.Nullable<byte> _Graduated;
		
		private string _DegreeAndMajor;
		
		public Education()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Applicant_ID", DbType="Int NOT NULL")]
		public int Applicant_ID
		{
			get
			{
				return this._Applicant_ID;
			}
			set
			{
				if ((this._Applicant_ID != value))
				{
					this._Applicant_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_School_ID", DbType="Int NOT NULL")]
		public int School_ID
		{
			get
			{
				return this._School_ID;
			}
			set
			{
				if ((this._School_ID != value))
				{
					this._School_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsAttendedFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> YearsAttendedFrom
		{
			get
			{
				return this._YearsAttendedFrom;
			}
			set
			{
				if ((this._YearsAttendedFrom != value))
				{
					this._YearsAttendedFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsAttendedTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> YearsAttendedTo
		{
			get
			{
				return this._YearsAttendedTo;
			}
			set
			{
				if ((this._YearsAttendedTo != value))
				{
					this._YearsAttendedTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Graduated", DbType="TinyInt")]
		public System.Nullable<byte> Graduated
		{
			get
			{
				return this._Graduated;
			}
			set
			{
				if ((this._Graduated != value))
				{
					this._Graduated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegreeAndMajor", DbType="VarChar(255)")]
		public string DegreeAndMajor
		{
			get
			{
				return this._DegreeAndMajor;
			}
			set
			{
				if ((this._DegreeAndMajor != value))
				{
					this._DegreeAndMajor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employer")]
	public partial class Employer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Employer_ID;
		
		private string _Name;
		
		private string _EmployerAddress;
		
		private string _PhoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployer_IDChanging(int value);
    partial void OnEmployer_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmployerAddressChanging(string value);
    partial void OnEmployerAddressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public Employer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employer_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Employer_ID
		{
			get
			{
				return this._Employer_ID;
			}
			set
			{
				if ((this._Employer_ID != value))
				{
					this.OnEmployer_IDChanging(value);
					this.SendPropertyChanging();
					this._Employer_ID = value;
					this.SendPropertyChanged("Employer_ID");
					this.OnEmployer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerAddress", DbType="VarChar(255)")]
		public string EmployerAddress
		{
			get
			{
				return this._EmployerAddress;
			}
			set
			{
				if ((this._EmployerAddress != value))
				{
					this.OnEmployerAddressChanging(value);
					this.SendPropertyChanging();
					this._EmployerAddress = value;
					this.SendPropertyChanged("EmployerAddress");
					this.OnEmployerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employment")]
	public partial class Employment
	{
		
		private int _Applicant_ID;
		
		private int _Employer_ID;
		
		private System.Nullable<byte> _MayWeContactCurrentEmployer;
		
		private System.Nullable<System.DateTime> _EmployedFrom;
		
		private System.Nullable<System.DateTime> _EmployedTo;
		
		private string _Supervisor;
		
		private string _Position;
		
		private string _StartingSalary;
		
		private string _EndingSalary;
		
		private string _ReasonForLeaving;
		
		private string _Responsibilities;
		
		public Employment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Applicant_ID", DbType="Int NOT NULL")]
		public int Applicant_ID
		{
			get
			{
				return this._Applicant_ID;
			}
			set
			{
				if ((this._Applicant_ID != value))
				{
					this._Applicant_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employer_ID", DbType="Int NOT NULL")]
		public int Employer_ID
		{
			get
			{
				return this._Employer_ID;
			}
			set
			{
				if ((this._Employer_ID != value))
				{
					this._Employer_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MayWeContactCurrentEmployer", DbType="TinyInt")]
		public System.Nullable<byte> MayWeContactCurrentEmployer
		{
			get
			{
				return this._MayWeContactCurrentEmployer;
			}
			set
			{
				if ((this._MayWeContactCurrentEmployer != value))
				{
					this._MayWeContactCurrentEmployer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployedFrom", DbType="Date")]
		public System.Nullable<System.DateTime> EmployedFrom
		{
			get
			{
				return this._EmployedFrom;
			}
			set
			{
				if ((this._EmployedFrom != value))
				{
					this._EmployedFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployedTo", DbType="Date")]
		public System.Nullable<System.DateTime> EmployedTo
		{
			get
			{
				return this._EmployedTo;
			}
			set
			{
				if ((this._EmployedTo != value))
				{
					this._EmployedTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="VarChar(255)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this._Supervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(255)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartingSalary", DbType="VarChar(255)")]
		public string StartingSalary
		{
			get
			{
				return this._StartingSalary;
			}
			set
			{
				if ((this._StartingSalary != value))
				{
					this._StartingSalary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndingSalary", DbType="VarChar(255)")]
		public string EndingSalary
		{
			get
			{
				return this._EndingSalary;
			}
			set
			{
				if ((this._EndingSalary != value))
				{
					this._EndingSalary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonForLeaving", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ReasonForLeaving
		{
			get
			{
				return this._ReasonForLeaving;
			}
			set
			{
				if ((this._ReasonForLeaving != value))
				{
					this._ReasonForLeaving = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsibilities", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Responsibilities
		{
			get
			{
				return this._Responsibilities;
			}
			set
			{
				if ((this._Responsibilities != value))
				{
					this._Responsibilities = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Expertise")]
	public partial class Expertise
	{
		
		private int _Applicant_ID;
		
		private int _Skill_ID;
		
		public Expertise()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Applicant_ID", DbType="Int NOT NULL")]
		public int Applicant_ID
		{
			get
			{
				return this._Applicant_ID;
			}
			set
			{
				if ((this._Applicant_ID != value))
				{
					this._Applicant_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skill_ID", DbType="Int NOT NULL")]
		public int Skill_ID
		{
			get
			{
				return this._Skill_ID;
			}
			set
			{
				if ((this._Skill_ID != value))
				{
					this._Skill_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Job")]
	public partial class Job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Job_ID;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJob_IDChanging(int value);
    partial void OnJob_IDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public Job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Job_ID
		{
			get
			{
				return this._Job_ID;
			}
			set
			{
				if ((this._Job_ID != value))
				{
					this.OnJob_IDChanging(value);
					this.SendPropertyChanging();
					this._Job_ID = value;
					this.SendPropertyChanged("Job_ID");
					this.OnJob_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobRequirement")]
	public partial class JobRequirement
	{
		
		private int _Job_ID;
		
		private int _Skill_ID;
		
		private string _Notes;
		
		public JobRequirement()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_ID", DbType="Int NOT NULL")]
		public int Job_ID
		{
			get
			{
				return this._Job_ID;
			}
			set
			{
				if ((this._Job_ID != value))
				{
					this._Job_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skill_ID", DbType="Int NOT NULL")]
		public int Skill_ID
		{
			get
			{
				return this._Skill_ID;
			}
			set
			{
				if ((this._Skill_ID != value))
				{
					this._Skill_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(20)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reference")]
	public partial class Reference : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Reference_ID;
		
		private System.Nullable<int> _YearsKnown;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReference_IDChanging(int value);
    partial void OnReference_IDChanged();
    partial void OnYearsKnownChanging(System.Nullable<int> value);
    partial void OnYearsKnownChanged();
    #endregion
		
		public Reference()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Reference_ID
		{
			get
			{
				return this._Reference_ID;
			}
			set
			{
				if ((this._Reference_ID != value))
				{
					this.OnReference_IDChanging(value);
					this.SendPropertyChanging();
					this._Reference_ID = value;
					this.SendPropertyChanged("Reference_ID");
					this.OnReference_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsKnown", DbType="Int")]
		public System.Nullable<int> YearsKnown
		{
			get
			{
				return this._YearsKnown;
			}
			set
			{
				if ((this._YearsKnown != value))
				{
					this.OnYearsKnownChanging(value);
					this.SendPropertyChanging();
					this._YearsKnown = value;
					this.SendPropertyChanged("YearsKnown");
					this.OnYearsKnownChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.School")]
	public partial class School : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _School_ID;
		
		private string _School_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSchool_IDChanging(int value);
    partial void OnSchool_IDChanged();
    partial void OnSchool_NameChanging(string value);
    partial void OnSchool_NameChanged();
    #endregion
		
		public School()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_School_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int School_ID
		{
			get
			{
				return this._School_ID;
			}
			set
			{
				if ((this._School_ID != value))
				{
					this.OnSchool_IDChanging(value);
					this.SendPropertyChanging();
					this._School_ID = value;
					this.SendPropertyChanged("School_ID");
					this.OnSchool_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_School_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string School_Name
		{
			get
			{
				return this._School_Name;
			}
			set
			{
				if ((this._School_Name != value))
				{
					this.OnSchool_NameChanging(value);
					this.SendPropertyChanging();
					this._School_Name = value;
					this.SendPropertyChanged("School_Name");
					this.OnSchool_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skill")]
	public partial class Skill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Skill_ID;
		
		private string _SkillName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSkill_IDChanging(int value);
    partial void OnSkill_IDChanged();
    partial void OnSkillNameChanging(string value);
    partial void OnSkillNameChanged();
    #endregion
		
		public Skill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skill_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Skill_ID
		{
			get
			{
				return this._Skill_ID;
			}
			set
			{
				if ((this._Skill_ID != value))
				{
					this.OnSkill_IDChanging(value);
					this.SendPropertyChanging();
					this._Skill_ID = value;
					this.SendPropertyChanged("Skill_ID");
					this.OnSkill_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkillName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SkillName
		{
			get
			{
				return this._SkillName;
			}
			set
			{
				if ((this._SkillName != value))
				{
					this.OnSkillNameChanging(value);
					this.SendPropertyChanging();
					this._SkillName = value;
					this.SendPropertyChanged("SkillName");
					this.OnSkillNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
